# Configuration for example scripts

create-onchain-attestation:
  # - schemaString: "string location, uint256 timestamp, string notes"
  #   schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
  #   fields:
  #     location: "New York"
  #     timestamp: 1633072800
  #     notes: "This is a private note."
  #   revocable: true
  # - schemaString: "string location, uint256 timestamp, string notes"
  #   revocable: true
  #   schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
  #   fields:
  #     location: "New York"
  #     timestamp: 1633072800
  #     notes: "This is a private note."
  - schemaString: "bytes32 eventId, int40[2][][] coordinates, string geometryType, string crs"
    schemaUid: "0xc04a24715ae76ee0eb73d7d985b7c4d13430c43c15d6cc71beb9896080b6b8d4"
    fields:
      eventId: "This is a really cool event!"
      coordinates:
        [
          [
            [-71099920287, 42357281791],
            [-71099920287, 42356854509],
            [-71099045620, 42356854509],
            [-71099045620, 42357281791],
            [-71099920287, 42357281791],
          ],
          [
            [-71099488030, 42356728102],
            [-71099488030, 42356496024],
            [-71099093256, 42356496024],
            [-71099093256, 42356728102],
            [-71099488030, 42356728102],
          ],
        ]
      geometryType: "Polygon"
      crs: "EPSG:4326"

create-offchain-attestation:
  - schemaUid: "0xb16fa048b0d597f5a821747eba64efa4762ee5143e9a80600d0005386edfc995"
    schemaString: "uint256 eventId, uint8 voteIndex"
    recipient: "0xFD50b031E778fAb33DfD2Fc3Ca66a1EeF0652165"
    revocable: true
    expirationTime: 0
    fields:
      eventId: 999
      voteIndex: 2

register-schema:
  # - schemaString: "string location, uint256 timestamp, string notes"
  #   revocable: true
  #   fields:
  #     location: "New York"
  #     timestamp: 1633072800
  #     notes: "This is a private note."
  - schemaString: "uint256 eventId, uint8 voteIndex"
    revocable: true

fetch-schema:
  - schemaUid: "0x5b647b9b8af5e81437c66f7d9334ee237bd0fc18134a54a5a9870cde8d4e4584"
  # - schemaString: "bytes32 eventId, int40[2][] coordinates, string geometryType" // Example to fetch schema UID by schema string

get-attestation:
  - attestationUid: "0x57321fea9593900bc3bc302b797d4f00595278f18de331d5a80c31815d2a0132"

revoke-attestation:
  - schemaUid: "0xb16fa048b0d597f5a821747eba64efa4762ee5143e9a80600d0005386edfc995"
    attestationUid: "0x57321fea9593900bc3bc302b797d4f00595278f18de331d5a80c31815d2a0132"

save-offchain-attestation:
  - schemaUid: "0xb16fa048b0d597f5a821747eba64efa4762ee5143e9a80600d0005386edfc995"
    recipient: "0xFD50b031E778fAb33DfD2Fc3Ca66a1EeF0652165"

load-offchain-attestation:
  - attestationUid: "0x57321fea9593900bc3bc302b797d4f00595278f18de331d5a80c31815d2a0132"

chained-attestation:
  - attestations:
      - schemaUid: "0xb16fa048b0d597f5a821747eba64efa4762ee5143e9a80600d0005386edfc995"
        schemaString: "uint256 eventId, uint8 voteIndex"
        referenceUid: "0x5b647b9b8af5e81437c66f7d9334ee237bd0fc18134a54a5a9870cde8d4e4584"
        fields:
          eventId: 999
          voteIndex: 2
      - schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
        referenceUid: "0x5b647b9b8af5e81437c66f7d9334ee237bd0fc18134a54a5a9870cde8d4e4584"
        schemaString: "string location, uint256 timestamp, string notes"
        revocable: true
        fields:
          location: "New York"
          timestamp: 1633072800
          notes: "This is a private note."

list-items:
  - recipient: "0x3074C8732366cE5DB80986aBA8FB69897872DdB9"
    referenceUid: "0xeeb457f8a9c5c9312010d69e0f7ab1119dcde9b5af421693939460ec6ce38fcf"

private-data-proofs:
  - schemaString: "string location, uint256 timestamp, string notes"
    schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
    fields:
      location: "New York"
      timestamp: 163307280
      notes: "This is a private note."
    revocable: true

# Add other example script configurations here, keyed by script name (without .ts)
# e.g.:
# register-schema:
#   - schema: "string message"
#     revocable: false
