# Configuration for example scripts

attest-onchain:
  # - schemaString: "string location, uint256 timestamp, string notes"
  #   schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
  #   fields:
  #     location: "New York"
  #     timestamp: 1633072800
  #     notes: "This is a private note."
  #   revocable: true
  - schemaString: "bytes32 eventId, int40[2][][] coordinates, string geometryType, string crs"
    schemaUid: "0xc04a24715ae76ee0eb73d7d985b7c4d13430c43c15d6cc71beb9896080b6b8d4"
    fields:
      eventId: "This is a really cool event!"
      coordinates:
        [
          [
            [-71099920287, 42357281791],
            [-71099920287, 42356854509],
            [-71099045620, 42356854509],
            [-71099045620, 42357281791],
            [-71099920287, 42357281791],
          ],
          [
            [-71099488030, 42356728102],
            [-71099488030, 42356496024],
            [-71099093256, 42356496024],
            [-71099093256, 42356728102],
            [-71099488030, 42356728102],
          ],
        ]
      geometryType: "Polygon"
      crs: "EPSG:4326"

attest-offchain:
  - schemaUid: "0xb16fa048b0d597f5a821747eba64efa4762ee5143e9a80600d0005386edfc995"
    schemaString: "uint256 eventId, uint8 voteIndex"
    recipient: "0xFD50b031E778fAb33DfD2Fc3Ca66a1EeF0652165"
    revocable: true
    expirationTime: 0
    fields:
      eventId: 999
      voteIndex: 2

register-schema:
  # - schemaString: "string location, uint256 timestamp, string notes"
  #   revocable: true
  #   fields:
  #     location: "New York"
  #     timestamp: 1633072800
  #     notes: "This is a private note."
  - schemaString: "string srs, string locationType, string location, uint8 specVersion"
    revocable: true

fetch-schema:
  - schemaUid: "0x5b647b9b8af5e81437c66f7d9334ee237bd0fc18134a54a5a9870cde8d4e4584"
  # - schemaString: "bytes32 eventId, int40[2][] coordinates, string geometryType" // Example to fetch schema UID by schema string

fetch-attestation:
  - attestationUid: "0x57321fea9593900bc3bc302b797d4f00595278f18de331d5a80c31815d2a0132"

revoke-attestation:
  - schemaUid: "0xb16fa048b0d597f5a821747eba64efa4762ee5143e9a80600d0005386edfc995"
    attestationUid: "0x57321fea9593900bc3bc302b797d4f00595278f18de331d5a80c31815d2a0132"

save-offchain-attestation:
  # - schemaString: "bytes32 eventId, int40[2][][] coordinates, string geometryType, string crs"
  #   schemaUid: "0xc04a24715ae76ee0eb73d7d985b7c4d13430c43c15d6cc71beb9896080b6b8d4"
  #   fields:
  #     eventId: "Enter an event name here"
  #     coordinates:
  #       [
  #         [
  #           [-71099920287, 42357281791],
  #           [-71099920287, 42356854509],
  #           [-71099045620, 42356854509],
  #           [-71099045620, 42357281791],
  #           [-71099920287, 42357281791],
  #         ],
  #         [
  #           [-71099488030, 42356728102],
  #           [-71099488030, 42356496024],
  #           [-71099093256, 42356496024],
  #           [-71099093256, 42356728102],
  #           [-71099488030, 42356728102],
  #         ],
  #       ]
  #     geometryType: "Polygon"
  #     crs: "EPSG:4326"
  - schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
    referenceUid: "0x5b647b9b8af5e81437c66f7d9334ee237bd0fc18134a54a5a9870cde8d4e4584"
    schemaString: "string location, uint256 timestamp, string notes"
    revocable: true
    fields:
      location: "New York"
      timestamp: 1633072800
      notes: "This is a private note."

load-offchain-attestation:
  # Below are query parameters for loading offchain attestations.
  # You can use any combination of the following parameters to filter the results:
  # - schemaUid: The UID of the schema used to create the attestation.
  # - recipient: The address of the recipient of the attestation.
  # - attestationUid: The UID of the attestation.
  # - referenceUid: The UID of the reference attestation (if applicable).
  #
  # - If you provide multiple parameters, the results will be filtered to match all of them.
  # - If you provide no parameters, all offchain attestations will be returned.
  # - Note: set parameters to empty strings if you don't want to filter by them.
  #
  # NOTE: If you haven't saved any offchain attestations, this will return an empty list.
  - schemaUid: ""
    recipient: ""
    attestationUid: ""
    referenceUid: ""

chained-attestation:
  - attestations:
      - schemaUid: "0xb16fa048b0d597f5a821747eba64efa4762ee5143e9a80600d0005386edfc995"
        schemaString: "uint256 eventId, uint8 voteIndex"
        referenceUid: "0x5b647b9b8af5e81437c66f7d9334ee237bd0fc18134a54a5a9870cde8d4e4584"
        fields:
          eventId: 999
          voteIndex: 2
      - schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
        referenceUid: "0x5b647b9b8af5e81437c66f7d9334ee237bd0fc18134a54a5a9870cde8d4e4584"
        schemaString: "string location, uint256 timestamp, string notes"
        revocable: true
        fields:
          location: "New York"
          timestamp: 1633072800
          notes: "This is a private note."

list-items:
  - recipient: "0x3074C8732366cE5DB80986aBA8FB69897872DdB9"
    referenceUid: "0xeeb457f8a9c5c9312010d69e0f7ab1119dcde9b5af421693939460ec6ce38fcf"

create-private-data-object:
  - schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
    schemaString: "string location, uint256 timestamp, string notes"
    fields:
      location: "New York"
      timestamp: 1633072800
      notes: "This is a private note."
    revocable: true

generate-private-data-proofs:
  - schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
    schemaString: "string location, uint256 timestamp, string notes"
    fields:
      location: "New York"
      timestamp: 163307280
      notes: "This is a private note."
    revocable: true
    fieldsToDisclose: ["location", "timestamp"]

generate-onchain-private-data-proofs:
  - schemaString: "bytes32 eventId, int40[2][][] coordinates, string geometryType, string crs"
    schemaUid: "0xc04a24715ae76ee0eb73d7d985b7c4d13430c43c15d6cc71beb9896080b6b8d4"
    fields:
      eventId: "Enter an event name here"
      coordinates:
        [
          [
            [-71099920287, 42357281791],
            [-71099920287, 42356854509],
            [-71099045620, 42356854509],
            [-71099045620, 42357281791],
            [-71099920287, 42357281791],
          ],
          [
            [-71099488030, 42356728102],
            [-71099488030, 42356496024],
            [-71099093256, 42356496024],
            [-71099093256, 42356728102],
            [-71099488030, 42356728102],
          ],
        ]
      geometryType: "Polygon"
      crs: "EPSG:4326"
    revocable: true
    fieldsToDisclose: ["geometryType", "crs"]

  # - schemaUid: "0xb08ebaac3deb3ed7e125d076eb7b0cbe4f0e66aff74d8dd38c6214fd9d162587"
  #   schemaString: "string location, uint256 timestamp, string notes"
  #   fields:
  #     location: "New York"
  #     timestamp: 163307280
  #     notes: "This is a private note."
  #   revocable: true
  #   fieldsToDisclose: ["location", "timestamp"]

gas-cost-comparison:
  # See `extras.md` for an alternative option to test.
  - fields:
      coordinates: |
        {
          "type": "FeatureCollection",
          "features":
            [
              {
                "type": "Feature",
                "properties": {},
                "geometry":
                  {
                    "coordinates":
                      [
                        [
                          [-71.09992028737877, 42.35728179069244],
                          [-71.09992028737877, 42.35685450937632],
                          [-71.09904562029875, 42.35685450937632],
                          [-71.09904562029875, 42.35728179069244],
                          [-71.09992028737877, 42.35728179069244]
                        ]
                      ],
                    "type": "Polygon"
                  }
              },
              {
                "type": "Feature",
                "properties": {},
                "geometry":
                  {
                    "coordinates":
                      [
                        [
                          [-71.09948802976496, 42.35672810199296],
                          [-71.09948802976496, 42.35649602365416],
                          [-71.0990932555289, 42.35649602365416],
                          [-71.0990932555289, 42.35672810199296],
                          [-71.09948802976496, 42.35672810199296]
                        ]
                      ],
                    "type": "Polygon"
                  }
              }
            ]
        }

event-checkin-workflow:
  - schemaString: "string srs, string locationType, string location, uint8 specVersion, string eventId, string ticketId, uint64 timestamp" # Replace with your actual schema string, e.g., "string eventId, string ticketId, uint64 timestamp, string geoJson"
    fields:
      srs: "EPSG:4326"
      locationType: "geoJson"
      specVersion: 1
      eventId: "Community Center Concert" # Replace with the actual event ID

event-checkin-workflow2:
  attestations:
    - schemaString: "string eventId, string ticketId, uint64 timestamp"
      # Fields that are are missing below are created in the script.
      fields:
        eventId: "Community Center Concert" # Replace with the actual event ID
        timestamp: 0
      revocable: true
    - schemaString: "string srs, string locationType, string location, uint8 specVersion, string eventId" # Replace with your actual schema string, e.g., "string eventId, string ticketId, uint64 timestamp, string geoJson"
      fields:
        srs: "EPSG:4326"
        locationType: "geoJson"
        specVersion: 1
        eventId: "Community Center Concert" # Replace with the actual event ID
      revocable: true
# Add other example script configurations here, keyed by script name (without .ts)
# e.g.:
# register-schema:
#   - schema: "string message"
#     revocable: false
